import { Injectable, signal } from '@angular/core';

import { environment } from '../../../environments/environment';

export type SupportedLanguage = 'zh-TW' | 'en-US' | 'ja-JP';

const translations: Record<SupportedLanguage, Record<string, string>> = {
  'zh-TW': {
    'shell.appName': '財務管理',
    'shell.systemTitle': '財務管理系統',
    'shell.versionMonolith': 'v1.0.0 Monolith',
    'shell.architectureMonolith': '傳統單體架構',
    'shell.menu.dashboard.label': '資產總覽',
    'shell.menu.dashboard.description': 'Dashboard - 圖表與統計',
    'shell.menu.bookkeeping.label': '快速記帳',
    'shell.menu.bookkeeping.description': 'Bookkeeping - 記帳功能',
    'shell.menu.currency.label': '匯率計算機',
    'shell.menu.currency.description': 'Currency Converter',
    'shell.menu.settings.label': '個人設定',
    'shell.menu.settings.description': 'Settings - 主題與偏好',
    'shell.language.button': '語言',
    'shell.language.current': '繁體中文',
    'Currency Converter': '匯率計算機',
    'Dashboard - 圖表與統計': 'Dashboard - 圖表與統計',
    'Bookkeeping - 記帳功能': 'Bookkeeping - 記帳功能',
    'Settings - 主題與偏好': 'Settings - 主題與偏好'
  },
  'en-US': {
    'shell.appName': 'Finance Workspace',
    'shell.systemTitle': 'Financial Operations Hub',
    'shell.versionMonolith': 'v1.0.0 Monolith',
    'shell.architectureMonolith': 'Traditional monolith',
    'shell.menu.dashboard.label': 'Portfolio Overview',
    'shell.menu.dashboard.description': 'Dashboard - charts and analytics',
    'shell.menu.bookkeeping.label': 'Quick Bookkeeping',
    'shell.menu.bookkeeping.description': 'Bookkeeping - daily transaction flow',
    'shell.menu.currency.label': 'FX Converter',
    'shell.menu.currency.description': 'Currency Converter',
    'shell.menu.settings.label': 'Preferences',
    'shell.menu.settings.description': 'Settings - themes and preferences',
    'shell.language.button': 'Language',
    'shell.language.current': 'English',
    '匯率計算機': 'FX Converter',
    '快速換算不同貨幣': 'Quickly convert between currencies',
    '來源貨幣': 'Base currency',
    '目標貨幣': 'Target currency',
    '金額': 'Amount',
    '更新匯率中...': 'Refreshing rates...',
    '匯率歷史': 'Exchange history',
    '匯率工作台': 'Currency workspace',
    '更新方式': 'Update mode',
    '匯率更新中': 'Updating rates',
    '使用 mock rates': 'Using mock rates',
    '新台幣': 'New Taiwan dollar',
    '美金': 'US dollar',
    '歐元': 'Euro',
    '日圓': 'Japanese yen',
    '韓元': 'Korean won',
    '人民幣': 'Chinese yuan',
    '港幣': 'Hong Kong dollar',
    '澳幣': 'Australian dollar',
    '英鎊': 'British pound',
    '帳目列表': 'Transaction list',
    '查看、編輯或刪除您所有的記帳紀錄': 'Review, edit, or remove all of your transaction records',
    '分析頁': 'Analytics',
    '重複交易': 'Recurring',
    '審核頁': 'Review',
    '對帳頁': 'Reconciliation',
    '資料來源': 'Data source',
    '本機交易服務': 'Local transaction service',
    '檢查模式': 'Inspection mode',
    '支援審核與對帳': 'Supports review and reconciliation',
    '匯入能力': 'Import capability',
    '可搭配 XLSX 流程': 'Works with the XLSX workflow',
    '收入': 'Income',
    '支出': 'Expense',
    '筆數': 'Records',
    '來源': 'Source',
    '延遲': 'Latency',
    '日期': 'Date',
    '類型': 'Type',
    '分類': 'Category',
    '幣別': 'Currency',
    '備註': 'Notes',
    '還沒有任何記帳紀錄。': 'No transactions yet.',
    '關鍵字': 'Keyword',
    '全部': 'All',
    '最低金額': 'Minimum amount',
    '排序欄位': 'Sort field',
    '排序方向': 'Sort direction',
    '分組方式': 'Group by',
    '由大到小 / 由新到舊': 'Descending / newest first',
    '由小到大 / 由舊到新': 'Ascending / oldest first',
    '月份': 'Month',
    '清除條件': 'Reset filters',
    '您確定要刪除這筆帳目嗎?': 'Are you sure you want to delete this transaction?',
    '載入資料中...': 'Loading data...',
    '總資產': 'Total assets',
    '月收入': 'Monthly income',
    '月支出': 'Monthly expense',
    '淨值': 'Net worth',
    '本月': 'Current month',
    '（非本月資料）': '(not current month)',
    '淨資產趨勢分析': 'Net worth trend analysis',
    '歷史資產變化': 'Historical asset changes',
    '近 6 個月': 'Last 6 months',
    '近 1 年': 'Last 1 year',
    '近 2 年': 'Last 2 years',
    '近 3 年': 'Last 3 years',
    '折線圖': 'Line chart',
    '長條圖': 'Bar chart',
    '載入圖表...': 'Loading chart...',
    '支出分類分析': 'Expense breakdown analysis',
    '查看本月': 'View current month',
    '模擬高運算場景：': 'High-compute simulation:',
    '此頁面包含複雜的圖表渲染與資料運算，用於測試微前端架構下的效能表現。': 'This page contains heavier chart rendering and data processing to stress-test the microfrontend architecture.',
    '儀表板洞察': 'Dashboard insights',
    '情境模擬': 'Scenario planning',
    '配置解讀': 'Allocation review',
    '資料模式': 'Data mode',
    '假資料即時推演': 'Live mock-data simulation',
    '圖表數量': 'Chart count',
    '2 組主視覺分析': 'Two primary visual analyses',
    '模擬能力': 'Simulation capability',
    '支援公式情境切換': 'Supports formula-based scenario switching',
    '儀表板洞察頁': 'Dashboard insights',
    '這一頁使用 component-store 整理多個資料來源，讓 dashboard 不只是一張總覽頁。': 'This page uses component-store to combine multiple data sources so the dashboard becomes more than a single overview.',
    '總覽': 'Overview',
    '載入分析資料中...': 'Loading analytics...',
    '平均月收入': 'Average monthly income',
    '平均月支出': 'Average monthly expense',
    '平均儲蓄率': 'Average savings rate',
    '最高支出類別': 'Top expense category',
    '未來六個月淨值推估': 'Projected net worth for the next 6 months',
    '洞察資料載入失敗：': 'Failed to load insights: ',
    '目前沒有可用的洞察資料。': 'No insight data is available right now.',
    '資產情境模擬': 'Asset scenario planning',
    '這一頁把 dashboard 往互動運算頁延伸，讓 TS 計算邏輯變重。': 'This page extends the dashboard into an interactive compute-heavy workspace.',
    '目前淨值': 'Current net worth',
    '月投資額': 'Monthly investment',
    '月支出變動': 'Monthly expense delta',
    '可用變數': 'Available variables',
    '保守情境公式': 'Conservative formula',
    '樂觀情境公式': 'Optimistic formula',
    '壓力情境公式': 'Stress formula',
    '重設公式': 'Reset formulas',
    '12 個月模擬': '12-month projection',
    '12 個月保守值': '12-month conservative value',
    '12 個月樂觀值': '12-month optimistic value',
    '12 個月壓力值': '12-month stress value',
    '資產配置解讀': 'Asset allocation review',
    '這一頁透過 facade 將洞察資料轉成配置觀點，讓 dashboard 更像一個子系統。': 'This page uses a facade to turn insights into allocation guidance.',
    '載入配置資料中...': 'Loading allocation data...',
    '配置資料載入失敗：': 'Failed to load allocation data: ',
    '目前沒有可用的配置解讀資料。': 'No allocation data is available right now.',
    '記帳分析頁': 'Bookkeeping analytics',
    '用 date-fns、fuse.js 與 schema 解析讓 bookkeeping 變成資料分析模組。': 'This page turns bookkeeping into an analytics module with date-fns, fuse.js, and schema parsing.',
    '交易列表': 'Transaction list',
    '記帳分析': 'Bookkeeping analytics',
    '交易審核': 'Transaction review',
    '交易對帳': 'Transaction reconciliation',
    '本月收入': 'This month income',
    '本月支出': 'This month expense',
    '模糊搜尋命中': 'Fuzzy-search matches',
    '重複交易候選': 'Recurring candidates',
    '這一頁把交易資料往規則化管理延伸，不只是 CRUD。': 'This page pushes transaction data toward rule-based management instead of plain CRUD.',
    '平均金額': 'Average amount',
    '出現次數': 'Occurrences',
    '最近日期': 'Most recent date',
    '交易審核頁': 'Transaction review',
    '把分析與規則候選拉到同一頁，形成 bookkeeping 的月結工作流。': 'This page combines analytics and rule candidates into a bookkeeping review workflow.',
    'Excel 工作簿': 'Excel workbook',
    '匯入 Excel': 'Import Excel',
    '匯出工作簿': 'Export workbook',
    '工作表': 'Sheets',
    '預覽列數': 'Preview rows',
    '本月摘要': 'Monthly summary',
    '重點類別': 'Focus category',
    'Exchange History': 'Exchange history',
    '匯率歷史頁': 'Exchange history',
    '這一頁使用 component-store 與 schema parsing 整理匯率快照與短期歷史。': 'This page uses component-store and schema parsing to organize snapshots and short-term FX history.',
    '匯率換算': 'Currency conversion',
    '最新匯率': 'Latest rate',
    'Currency Workspace': 'Currency workspace',
    '設定首頁': 'Settings home',
    '通知規則': 'Notification rules',
    '工作台偏好': 'Workspace preferences',
    '這裡把匯率模組拉成資料視角，而不是只有單次換算。': 'This page turns the FX module into a data-centric workspace instead of a one-off converter.',
    '基準幣別': 'Base currency',
    '最近資料日': 'Latest data date',
    '個人設定': 'Preferences',
    '自訂您的應用程式偏好': 'Customize your application preferences',
    '深色模式': 'Dark mode',
    '啟用深色背景以減輕眼睛疲勞': 'Enable a dark background to reduce eye strain',
    '預設貨幣': 'Default currency',
    '設定記帳預設使用的貨幣單位': 'Choose the default currency used by bookkeeping',
    '選擇貨幣': 'Choose currency',
    '主題模式': 'Theme mode',
    '淺色模式': 'Light mode',
    '設定入口': 'Settings entry',
    '通知與工作台': 'Notifications and workspace',
    'Notification Rules': 'Notification rules',
    '通知設定頁': 'Notification settings',
    '這一頁把設定模組往表單規則與偏好預覽延伸。': 'This page extends settings into form rules and preference previews.',
    '通知管道': 'Notification channel',
    '頻率': 'Frequency',
    '每日': 'Daily',
    '每週': 'Weekly',
    '每月': 'Monthly',
    '警示門檻': 'Alert threshold',
    '規則預覽': 'Rule preview',
    '切換預覽': 'Toggle preview',
    '已停用': 'Disabled',
    'email': 'Email',
    'app': 'App',
    'Settings Workspace': 'Settings workspace',
    '設定工作台': 'Settings workspace',
    '這一頁把 fuse 搜尋與 zod 驗證放進設定模組，讓 TS 複雜度更高。': 'This page adds fuse search and zod validation to the settings module for heavier TS logic.',
    '搜尋設定': 'Search settings',
    '啟用 Email Digest': 'Enable email digest',
    '啟用 Compact Mode': 'Enable compact mode',
    '每週檢視日': 'Weekly review day',
    '預設首頁': 'Default landing page',
    '套用目前配色': 'Apply current palette',
    '原始預設': 'Original default',
    '回到系統一開始提供的預設配色。': 'Return to the palette that ships with the default system setup.',
    '驗證設定': 'Validate settings',
    '預設顏色組': 'Preset palettes',
    '先選一組基底，再視需要微調各部位顏色。': 'Start from a preset, then fine-tune each area as needed.',
    '各部位選色器': 'Per-area color pickers',
    '針對背景、工具列、側欄、強調色與文字做細部調整。': 'Fine-tune background, toolbar, sidebar, accent, and text colors.',
    '即時預覽': 'Live preview',
    '預覽 toolbar、sidebar、surface 與 accent 的組合效果。': 'Preview how toolbar, sidebar, surface, and accent work together.',
    'Monaco 進階設定編輯器': 'Advanced Monaco settings editor',
    '直接編輯整份 user settings JSON，讓設定頁承載更重的編輯器與驗證流程。': 'Edit the full user settings JSON directly to add a heavier editor and validation workflow.',
    '載入整份設定': 'Load full settings',
    '驗證 JSON': 'Validate JSON',
    '套用編輯器內容': 'Apply editor content',
    '尚未驗證': 'Not validated yet',
    'Monaco 編輯器準備中': 'Preparing Monaco editor',
    '尚未驗證 JSON 編輯器內容': 'JSON editor content has not been validated yet',
    '找不到 Monaco 掛載區域': 'Monaco mount area was not found',
    'Monaco 編輯器已載入，可直接編輯工作台 JSON': 'Monaco editor is ready and can edit the workspace JSON directly',
    '已套用自訂配色': 'Custom palette applied',
    '設定格式有效': 'Settings format is valid',
    '設定格式無效': 'Settings format is invalid',
    '已同步目前整份設定到編輯器': 'The current full settings have been synced into the editor',
    '整份設定 JSON 格式有效': 'The full settings JSON is valid',
    '編輯器 JSON 無效': 'The editor JSON is invalid',
    '已從編輯器套用整份設定': 'Applied the full settings from the editor',
    '無法套用編輯器設定': 'Unable to apply the editor settings',
    'Ocean Balance': 'Ocean Balance',
    '冷藍工作台，適合 dashboard 與長時間閱讀。': 'A cool-blue workspace suited for dashboards and long reading sessions.',
    'Sunset Ledger': 'Sunset Ledger',
    '暖色對比高，讓 bookkeeping 與提醒操作更明顯。': 'Warm high-contrast tones that make bookkeeping and reminder actions stand out.',
    'Forest Ops': 'Forest Ops',
    '偏深綠與石墨灰，適合多頁面切換與分析場景。': 'Deep green with graphite gray, suitable for multi-page flows and analytics.',
    'Graphite Signal': 'Graphite Signal',
    '中性灰配高亮 accent，適合偏深色操作風格。': 'Neutral gray with a bright accent, suitable for a darker operating style.',
    'Fake API Reconciliation': 'Fake API Reconciliation',
    '交易對帳頁': 'Transaction reconciliation',
    'Excel 解析': 'Excel parsing',
    '匯入工作簿': 'Import workbook',
    '匯出對帳簿': 'Export reconciliation workbook',
    '列數': 'Rows',
    'API 狀態': 'API status',
    '抓取時間': 'Fetched at',
    '總額摘要': 'Total summary',
    '淨額': 'Net amount',
    '異常筆數': 'Anomaly count',
    '待檢查': 'Pending review',
    '回傳數': 'Returned rows',
    '總筆數': 'Total rows',
    '分組結果': 'Grouped results',
    '異常候選': 'Anomaly candidates',
    '匯出 Preview': 'Export preview',
    '尚未匯入對帳工作簿': 'No reconciliation workbook imported yet',
    '頁面背景': 'Page background',
    '控制主要內容區的大面積底色。': 'Controls the main content background.',
    '卡片表面': 'Card surface',
    '控制卡片與面板的底色層級。': 'Controls the base color of cards and panels.',
    '頂部工具列': 'Top toolbar',
    '控制 app toolbar 與標題列主色。': 'Controls the main color of the app toolbar and title bar.',
    '側欄背景': 'Sidebar background',
    '控制導覽列與 footer 色調。': 'Controls the tone of navigation and footer areas.',
    '強調色': 'Accent color',
    '控制啟用態、按鈕與標記重點色。': 'Controls active states, buttons, and highlighted accents.',
    '主要文字': 'Primary text',
    '控制版面主要文字與對比。': 'Controls primary text color and contrast.',
    'Finance Workspace': 'Finance workspace',
    'Dashboard': 'Dashboard',
    'Bookkeeping': 'Bookkeeping',
    'Settings': 'Settings',
    'Accent Block': 'Accent block',
    'Cards and panel surfaces follow the configured palette.': 'Cards and panel surfaces follow the configured palette.',
    '快速記帳': 'Quick bookkeeping',
    '編輯帳目': 'Edit transaction',
    '透過多步驟表單，快速記錄您的收入或支出': 'Use a multi-step form to quickly record income or expenses',
    '類型與分類': 'Type and category',
    '下一步': 'Next',
    '金額與日期': 'Amount and date',
    '例如: 150': 'Example: 150',
    '上一步': 'Previous',
    '備註與預覽': 'Notes and preview',
    '備註 (選填)': 'Notes (optional)',
    '例如: 與朋友聚餐': 'Example: dinner with friends',
    '確認資料': 'Confirm details',
    '無': 'None',
    '更新': 'Update',
    '完成': 'Done'
  },
  'ja-JP': {
    'shell.appName': '財務ワークスペース',
    'shell.systemTitle': '財務オペレーションハブ',
    'shell.versionMonolith': 'v1.0.0 Monolith',
    'shell.architectureMonolith': '従来型モノリス',
    'shell.menu.dashboard.label': '資産ダッシュボード',
    'shell.menu.dashboard.description': 'Dashboard - チャートと分析',
    'shell.menu.bookkeeping.label': 'クイック記帳',
    'shell.menu.bookkeeping.description': 'Bookkeeping - 日次取引フロー',
    'shell.menu.currency.label': '為替コンバーター',
    'shell.menu.currency.description': 'Currency Converter',
    'shell.menu.settings.label': '個人設定',
    'shell.menu.settings.description': 'Settings - テーマと設定',
    'shell.language.button': '言語',
    'shell.language.current': '日本語',
    '匯率計算機': '為替コンバーター',
    '快速換算不同貨幣': '異なる通貨をすばやく換算します',
    '來源貨幣': '基準通貨',
    '目標貨幣': '換算先通貨',
    '金額': '金額',
    '更新匯率中...': '為替レートを更新中...',
    '匯率歷史': '為替履歴',
    '匯率工作台': '為替ワークスペース',
    '更新方式': '更新方式',
    '匯率更新中': 'レート更新中',
    '使用 mock rates': 'モックレートを使用',
    '新台幣': '台湾ドル',
    '美金': '米ドル',
    '歐元': 'ユーロ',
    '日圓': '日本円',
    '韓元': '韓国ウォン',
    '人民幣': '人民元',
    '港幣': '香港ドル',
    '澳幣': '豪ドル',
    '英鎊': '英ポンド',
    '帳目列表': '取引一覧',
    '查看、編輯或刪除您所有的記帳紀錄': 'すべての取引記録を確認、編集、削除できます',
    '分析頁': '分析',
    '重複交易': '定期取引',
    '審核頁': 'レビュー',
    '對帳頁': '照合',
    '資料來源': 'データソース',
    '本機交易服務': 'ローカル取引サービス',
    '檢查模式': 'チェックモード',
    '支援審核與對帳': 'レビューと照合に対応',
    '匯入能力': 'インポート機能',
    '可搭配 XLSX 流程': 'XLSX ワークフローと連携可能',
    '收入': '収入',
    '支出': '支出',
    '筆數': '件数',
    '來源': 'ソース',
    '延遲': '遅延',
    '日期': '日付',
    '類型': '種類',
    '分類': 'カテゴリ',
    '幣別': '通貨',
    '備註': 'メモ',
    '還沒有任何記帳紀錄。': 'まだ取引記録はありません。',
    '關鍵字': 'キーワード',
    '全部': 'すべて',
    '最低金額': '最低金額',
    '排序欄位': '並び替え項目',
    '排序方向': '並び順',
    '分組方式': 'グループ化',
    '由大到小 / 由新到舊': '降順 / 新しい順',
    '由小到大 / 由舊到新': '昇順 / 古い順',
    '月份': '月',
    '清除條件': '条件をリセット',
    '您確定要刪除這筆帳目嗎?': 'この取引を削除してもよろしいですか?',
    '載入資料中...': 'データを読み込み中...',
    '總資產': '総資産',
    '月收入': '月間収入',
    '月支出': '月間支出',
    '淨值': '純資産',
    '本月': '今月',
    '（非本月資料）': '（今月以外のデータ）',
    '淨資產趨勢分析': '純資産トレンド分析',
    '歷史資產變化': '資産の推移',
    '近 6 個月': '直近6か月',
    '近 1 年': '直近1年',
    '近 2 年': '直近2年',
    '近 3 年': '直近3年',
    '折線圖': '折れ線グラフ',
    '長條圖': '棒グラフ',
    '載入圖表...': 'グラフを読み込み中...',
    '支出分類分析': '支出カテゴリ分析',
    '查看本月': '今月を見る',
    '模擬高運算場景：': '高負荷シミュレーション:',
    '此頁面包含複雜的圖表渲染與資料運算，用於測試微前端架構下的效能表現。': 'このページには重いチャート描画とデータ計算が含まれ、マイクロフロントエンド構成の性能確認に使われます。',
    '儀表板洞察': 'ダッシュボード洞察',
    '情境模擬': 'シナリオ計画',
    '配置解讀': '配分レビュー',
    '資料模式': 'データモード',
    '假資料即時推演': 'モックデータ即時シミュレーション',
    '圖表數量': 'チャート数',
    '2 組主視覺分析': '主要な可視化を2種搭載',
    '模擬能力': 'シミュレーション機能',
    '支援公式情境切換': '数式ベースのシナリオ切替に対応',
    '儀表板洞察頁': 'ダッシュボード洞察',
    '這一頁使用 component-store 整理多個資料來源，讓 dashboard 不只是一張總覽頁。': 'このページでは component-store を使って複数のデータソースを統合し、ダッシュボードを単なる概要画面以上にしています。',
    '總覽': '概要',
    '載入分析資料中...': '分析データを読み込み中...',
    '平均月收入': '平均月収',
    '平均月支出': '平均月支出',
    '平均儲蓄率': '平均貯蓄率',
    '最高支出類別': '最大支出カテゴリ',
    '未來六個月淨值推估': '今後6か月の純資産予測',
    '洞察資料載入失敗：': '洞察データの読み込みに失敗しました: ',
    '目前沒有可用的洞察資料。': '利用可能な洞察データはありません。',
    '資產情境模擬': '資産シナリオ計画',
    '這一頁把 dashboard 往互動運算頁延伸，讓 TS 計算邏輯變重。': 'このページでは dashboard を対話的な計算ページへ拡張し、TS ロジックを重くしています。',
    '目前淨值': '現在の純資産',
    '月投資額': '月間投資額',
    '月支出變動': '月間支出変動',
    '可用變數': '使用可能な変数',
    '保守情境公式': '保守シナリオ式',
    '樂觀情境公式': '楽観シナリオ式',
    '壓力情境公式': 'ストレスシナリオ式',
    '重設公式': '数式をリセット',
    '12 個月模擬': '12か月シミュレーション',
    '12 個月保守值': '12か月保守値',
    '12 個月樂觀值': '12か月楽観値',
    '12 個月壓力值': '12か月ストレス値',
    '資產配置解讀': '資産配分レビュー',
    '這一頁透過 facade 將洞察資料轉成配置觀點，讓 dashboard 更像一個子系統。': 'このページでは facade によって洞察データを配分ビューへ変換し、dashboard をより独立したサブシステムらしくしています。',
    '載入配置資料中...': '配分データを読み込み中...',
    '配置資料載入失敗：': '配分データの読み込みに失敗しました: ',
    '目前沒有可用的配置解讀資料。': '利用可能な配分データはありません。',
    '記帳分析頁': '記帳分析',
    '用 date-fns、fuse.js 與 schema 解析讓 bookkeeping 變成資料分析模組。': 'date-fns、fuse.js、schema 解析を使って bookkeeping を分析モジュールへ拡張しています。',
    '交易列表': '取引一覧',
    '記帳分析': '記帳分析',
    '交易審核': '取引レビュー',
    '交易對帳': '取引照合',
    '本月收入': '今月の収入',
    '本月支出': '今月の支出',
    '模糊搜尋命中': '曖昧検索ヒット',
    '重複交易候選': '定期取引候補',
    '這一頁把交易資料往規則化管理延伸，不只是 CRUD。': 'このページでは取引データを CRUD 以上のルールベース管理へ拡張しています。',
    '平均金額': '平均金額',
    '出現次數': '出現回数',
    '最近日期': '最新日付',
    '交易審核頁': '取引レビュー',
    '把分析與規則候選拉到同一頁，形成 bookkeeping 的月結工作流。': '分析とルール候補を1ページにまとめ、bookkeeping の月次レビュー導線を作っています。',
    'Excel 工作簿': 'Excel ブック',
    '匯入 Excel': 'Excel を取り込む',
    '匯出工作簿': 'ブックを出力',
    '工作表': 'シート',
    '預覽列數': 'プレビュー行数',
    '本月摘要': '今月の概要',
    '重點類別': '注目カテゴリ',
    'Exchange History': '為替履歴',
    '匯率歷史頁': '為替履歴',
    '這一頁使用 component-store 與 schema parsing 整理匯率快照與短期歷史。': 'このページでは component-store と schema parsing を使ってレートのスナップショットと短期履歴を整理しています。',
    '匯率換算': '通貨換算',
    '最新匯率': '最新レート',
    'Currency Workspace': '為替ワークスペース',
    '這裡把匯率模組拉成資料視角，而不是只有單次換算。': 'このページでは FX モジュールを単発換算ではなくデータ視点のワークスペースにしています。',
    '基準幣別': '基準通貨',
    '最近資料日': '最新データ日',
    '個人設定': '個人設定',
    '自訂您的應用程式偏好': 'アプリケーション設定をカスタマイズします',
    '深色模式': 'ダークモード',
    '啟用深色背景以減輕眼睛疲勞': '目の負担を減らすためダーク背景を有効化します',
    '預設貨幣': '既定通貨',
    '設定記帳預設使用的貨幣單位': '記帳で使う既定通貨を設定します',
    '選擇貨幣': '通貨を選択',
    '主題模式': 'テーマモード',
    '淺色模式': 'ライトモード',
    '設定入口': '設定入口',
    '通知與工作台': '通知とワークスペース',
    'Notification Rules': '通知ルール',
    '通知設定頁': '通知設定',
    '這一頁把設定模組往表單規則與偏好預覽延伸。': 'このページでは設定モジュールをフォームルールと設定プレビューへ拡張しています。',
    '設定首頁': '設定ホーム',
    '通知規則': '通知ルール',
    '工作台偏好': 'ワークスペース設定',
    '通知管道': '通知チャネル',
    '頻率': '頻度',
    '每日': '毎日',
    '每週': '毎週',
    '每月': '毎月',
    '警示門檻': 'アラートしきい値',
    '規則預覽': 'ルールプレビュー',
    '切換預覽': 'プレビュー切替',
    '已停用': '無効',
    'email': 'Email',
    'app': 'App',
    'Settings Workspace': '設定ワークスペース',
    '設定工作台': '設定ワークスペース',
    '這一頁把 fuse 搜尋與 zod 驗證放進設定模組，讓 TS 複雜度更高。': 'このページでは fuse 検索と zod 検証を設定モジュールに入れ、TS の複雑度を上げています。',
    '搜尋設定': '設定を検索',
    '啟用 Email Digest': 'Email Digest を有効化',
    '啟用 Compact Mode': 'Compact Mode を有効化',
    '每週檢視日': '週次レビュー日',
    '預設首頁': '既定ホーム',
    '套用目前配色': '現在の配色を適用',
    '原始預設': '初期プリセット',
    '回到系統一開始提供的預設配色。': 'システム初期状態の既定配色に戻します。',
    '驗證設定': '設定を検証',
    '預設顏色組': '既定カラーパレット',
    '先選一組基底，再視需要微調各部位顏色。': 'まずプリセットを選び、必要に応じて各部位の色を微調整します。',
    '各部位選色器': '部位別カラーピッカー',
    '針對背景、工具列、側欄、強調色與文字做細部調整。': '背景、ツールバー、サイドバー、アクセント、文字色を細かく調整します。',
    '即時預覽': 'ライブプレビュー',
    '預覽 toolbar、sidebar、surface 與 accent 的組合效果。': 'toolbar、sidebar、surface、accent の組み合わせを確認します。',
    'Monaco 進階設定編輯器': 'Monaco 詳細設定エディター',
    '直接編輯整份 user settings JSON，讓設定頁承載更重的編輯器與驗證流程。': 'user settings JSON 全体を直接編集し、より重いエディターと検証フローを設定ページに載せます。',
    '載入整份設定': '設定全体を読み込む',
    '驗證 JSON': 'JSON を検証',
    '套用編輯器內容': 'エディター内容を適用',
    '尚未驗證': '未検証',
    'Monaco 編輯器準備中': 'Monaco エディターを準備中',
    '尚未驗證 JSON 編輯器內容': 'JSON エディター内容はまだ検証されていません',
    '找不到 Monaco 掛載區域': 'Monaco のマウント領域が見つかりません',
    'Monaco 編輯器已載入，可直接編輯工作台 JSON': 'Monaco エディターの準備ができ、ワークスペース JSON を直接編集できます',
    '已套用自訂配色': 'カスタム配色を適用しました',
    '設定格式有效': '設定形式は有効です',
    '設定格式無效': '設定形式が無効です',
    '已同步目前整份設定到編輯器': '現在の全設定をエディターへ同期しました',
    '整份設定 JSON 格式有效': '設定 JSON 全体の形式は有効です',
    '編輯器 JSON 無效': 'エディター JSON が無効です',
    '已從編輯器套用整份設定': 'エディターから全設定を適用しました',
    '無法套用編輯器設定': 'エディター設定を適用できません',
    'Ocean Balance': 'Ocean Balance',
    '冷藍工作台，適合 dashboard 與長時間閱讀。': 'ダッシュボードや長時間の閲覧に向いたクールブルーの配色です。',
    'Sunset Ledger': 'Sunset Ledger',
    '暖色對比高，讓 bookkeeping 與提醒操作更明顯。': '暖色でコントラストが高く、記帳や通知操作を目立たせます。',
    'Forest Ops': 'Forest Ops',
    '偏深綠與石墨灰，適合多頁面切換與分析場景。': '深い緑とグラファイトグレーで、多画面遷移や分析に向いています。',
    'Graphite Signal': 'Graphite Signal',
    '中性灰配高亮 accent，適合偏深色操作風格。': '中立グレーに明るいアクセントを合わせた、ややダーク寄りの操作スタイル向けです。',
    'Fake API Reconciliation': 'Fake API Reconciliation',
    '交易對帳頁': '取引照合',
    'Excel 解析': 'Excel 解析',
    '匯入工作簿': 'ブックを取り込む',
    '匯出對帳簿': '照合ブックを出力',
    '列數': '行数',
    'API 狀態': 'API 状態',
    '抓取時間': '取得時刻',
    '總額摘要': '合計概要',
    '淨額': '純額',
    '異常筆數': '異常件数',
    '待檢查': '確認待ち',
    '回傳數': '返却件数',
    '總筆數': '総件数',
    '分組結果': 'グループ結果',
    '異常候選': '異常候補',
    '匯出 Preview': '出力プレビュー',
    '尚未匯入對帳工作簿': '照合ワークブックはまだ取り込まれていません',
    '頁面背景': 'ページ背景',
    '控制主要內容區的大面積底色。': 'メインコンテンツの背景色を制御します。',
    '卡片表面': 'カード表面',
    '控制卡片與面板的底色層級。': 'カードとパネルの背景色を制御します。',
    '頂部工具列': '上部ツールバー',
    '控制 app toolbar 與標題列主色。': 'アプリツールバーとタイトルバーの主色を制御します。',
    '側欄背景': 'サイドバー背景',
    '控制導覽列與 footer 色調。': 'ナビゲーションとフッターの色調を制御します。',
    '強調色': 'アクセント色',
    '控制啟用態、按鈕與標記重點色。': 'アクティブ状態、ボタン、強調表示の色を制御します。',
    '主要文字': '主要文字',
    '控制版面主要文字與對比。': '主要テキストとコントラストを制御します。',
    'Finance Workspace': '財務ワークスペース',
    'Dashboard': 'ダッシュボード',
    'Bookkeeping': '記帳',
    'Settings': '設定',
    'Accent Block': 'アクセントブロック',
    'Cards and panel surfaces follow the configured palette.': 'カードとパネルは設定されたパレットに従います。',
    '快速記帳': 'クイック記帳',
    '編輯帳目': '取引を編集',
    '透過多步驟表單，快速記錄您的收入或支出': '多段ステップフォームで収入や支出をすばやく記録します',
    '類型與分類': '種類とカテゴリ',
    '下一步': '次へ',
    '金額與日期': '金額と日付',
    '例如: 150': '例: 150',
    '上一步': '戻る',
    '備註與預覽': 'メモとプレビュー',
    '備註 (選填)': 'メモ（任意）',
    '例如: 與朋友聚餐': '例: 友人との食事',
    '確認資料': '内容確認',
    '無': 'なし',
    '更新': '更新',
    '完成': '完了'
  }
};

export type TranslationKey = string;

export interface LanguageOption {
  code: SupportedLanguage;
  nativeLabel: string;
  englishLabel: string;
}

const supportedLanguages: LanguageOption[] = [
  { code: 'zh-TW', nativeLabel: '繁體中文', englishLabel: 'Traditional Chinese' },
  { code: 'en-US', nativeLabel: 'English', englishLabel: 'English' },
  { code: 'ja-JP', nativeLabel: '日本語', englishLabel: 'Japanese' }
];

const storageKey = 'workspace.language';

const isSupportedLanguage = (value: string | null | undefined): value is SupportedLanguage =>
  value === 'zh-TW' || value === 'en-US' || value === 'ja-JP';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly supportedLanguages = supportedLanguages;
  readonly currentLanguage = signal<SupportedLanguage>(this.resolveInitialLanguage());

  constructor() {
    this.applyLanguage(this.currentLanguage());
  }

  translate(key: TranslationKey): string {
    return translations[this.currentLanguage()][key] ?? translations['zh-TW'][key] ?? key;
  }

  setLanguage(language: SupportedLanguage): void {
    this.currentLanguage.set(language);
    this.applyLanguage(language);
  }

  getLanguageOption(language: SupportedLanguage): LanguageOption {
    return this.supportedLanguages.find((option) => option.code === language) ?? this.supportedLanguages[0];
  }

  private resolveInitialLanguage(): SupportedLanguage {
    const storedLanguage = this.readStoredLanguage();
    if (storedLanguage) {
      return storedLanguage;
    }

    return isSupportedLanguage(environment.defaultLanguage) ? environment.defaultLanguage : 'zh-TW';
  }

  private applyLanguage(language: SupportedLanguage): void {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }

    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(storageKey, language);
    }
  }

  private readStoredLanguage(): SupportedLanguage | null {
    if (typeof localStorage === 'undefined') {
      return null;
    }

    const storedLanguage = localStorage.getItem(storageKey);
    return isSupportedLanguage(storedLanguage) ? storedLanguage : null;
  }
}